name: logto
description: 'The better identity infrastructure for developers and the open-source alternative to Auth0.'
tags:
- login
source: https://github.com/logto-io/logto
website: https://logto.io
icon: https://avatars.githubusercontent.com/u/84981374?s=200&v=4
